### ISSUE TITLE
Queue size in read

### ISSUE THREAD

**Issue by ErniBrown** [SimonCahill/libsockcanpp#14]
https://github.com/SimonCahill/libsockcanpp/blob/621383ebefab3c154c05778315acc7e781924fdb/src/CanDriver.cpp#L111

There's an error here. Select does not return the size of the queue, only the number of file descriptors that are ready for reading/writing. So if you want to read all the messages you need to repeat the readMessage  until it returns 0 bytes read. Or maybe you can do a ioctl call to FIONREAD, but I have not tested this

https://man7.org/linux/man-pages/man2/select.2.html

**Comment by SimonCahill** [comment]
You're absolutely right.

I'll see when I have time to sort this out.

Thanks for the heads-up!

**Comment by SimonCahill** [comment]
I have made the necessary changes to the devel branch for this issue. I'll try and test the changes in the next few days.

If you have the time and can test it, I'd be grateful!

**Comment by petertheprocess** [comment]
```
if (_read_socket->waitForMessages(1000ms)) {
            auto msgs = _read_socket->readQueuedMessages();
            size_t msg_qcount = msgs.size();
            if (msg_qcount > 0) {
                spdlog::debug("Queue Processing {} CAN messages", msg_qcount);
            }
            int32_t msg_count = _read_socket->getMessageQueueSize();
            if (msg_count > 0) {
                spdlog::debug("Processing {} CAN messages", msg_count);
            }
......
........
.......
```
I have this code, the msgs.size() will get the right number, but getMessageQueueSize() is always 0.

**Comment by SimonCahill** [comment]
This can happen if the interface doesn't support `FIONREAD`:

```cpp
if (retCode == 0) {
    m_queueSize = static_cast<int32_t>(std::ceil(bytesAvailable / sizeof(can_frame)));
} else {
    m_queueSize = 0;
    // vcan interfaces don't support FIONREAD. So fall back to
    // using alternate implementation in readQueuedMessages().
    m_canReadQueueSize = false;
}
```

Are you reading from a CAN socket or vcan?
Could you open a new issue?

**Comment by petertheprocess** [comment]
> Are you reading from a CAN socket or vcan? Could you open a new issue?

I am using Jetson Orin, will test it when I finished things on my hand.

**Comment by SimonCahill** [comment]
Interesting. I've tested the library on an AGX Xavier without issue.
