### ISSUE TITLE
CanMessage issues

### ISSUE THREAD

**Issue by lilgrant22** [SimonCahill/libsockcanpp#16]
I'm having two separate issues with CanMessages. First, when reading in a message and calling the getCanId function, the CanId is off but barely. For example reading in a CanMessage with id = 0x18022080, the returned CanId from getCanId is 0x98022080. Similarly when sending a CanMessage, the data being sent is off as well. Example: The data to be sent should be 60 00 12 04 00 00 00 in hex, but what is being send is 70 17 B0 04 00 FF 00. Any ideas on what could be going on?

**Comment by lilgrant22** [comment]
Here's my source code, stripped down.

`#include <CanDriver.hpp>
#include <exceptions/CanException.hpp>
#include <exceptions/CanInitException.hpp>
#include <exceptions/InvalidSocketException.hpp>
#include <exceptions/CanCloseException.hpp>

using sockcanpp::CanDriver;
using sockcanpp::CanId;
using sockcanpp::exceptions::CanException;
using sockcanpp::exceptions::CanInitException;
using sockcanpp::exceptions::InvalidSocketException;
using sockcanpp::CanMessage;

enum {
  
    STATE1      = 0x8C602080,
    STATE2      = 0x8C612080,
    STATE3      = 0x8C622080, 
    STATEA      = 0x8C702080, 
    STATEB      = 0x8C712080, 
    STATEC      = 0x8C722080, 
    HEARTBEAT   = 0x98022080, 
    SEND1       = 0x0C648020, 
    ACK         = 0x0CE88020

};
 
double          x = 60;
double          y = 120;
unsigned char   z = 1;
bool            a = 0;
bool            b = 0;

}

void sendFrame( CanDriver* &driver ) {
    
    can_frame transmit_message;
    transmit_message.can_dlc = 8;
    
    unsigned short tmp = static_cast<unsigned short>( x / 0.01 );
    memcpy( &transmit_message.data[0], &tmp, sizeof( tmp ) );
    tmp = static_cast<unsigned short>( y / 0.1 );
    memcpy( &transmit_message.data[2], &tmp, sizeof( tmp ) );
    
    transmit_message.data[4] = 0;
    transmit_message.data[4] = ( static_cast<unsigned char>( z ) << 2 );
    transmit_message.data[4] += ( static_cast<unsigned char>( a ) << 1 );
    transmit_message.data[4] += ( static_cast<unsigned char>( b ) ); 
    
    transmit_message.can_id = SYS_CONT_DATA1;

    CanMessage sys_cont_data1 ( transmit_message );
    driver->sendMessage( sys_cont_data1 );

}

void receiveCanFrame( CanDriver* &driver ) {
        
    if ( !driver->waitForMessages( ) ) {  }
        
      std::queue<CanMessage> CanMessages = driver->readQueuedMessages( );

      while( !CanMessages.empty( ) ) {

          auto msg = CanMessages.front( );
          CanMessages.pop( );

          if( msg.getCanId( ) == HEARTBEAT ) {
              
              try {
              
                CanMessage send_ACK ( 0x0CE88020, "ACK" );
                driver->sendMessage( send_ACK );

                return;
                
              } catch ( CanException& ex ) {
              
                std::cerr << "Failed to send ACK Message (void receiveCanFrame( )): " << ex.what( ) << std::endl;
              
              }

          }
          
}


int main( ) {
    
    CanDriver* canDriver;
    canDriver = new CanDriver( "can0", CAN_RAW );
    
    
    while ( true ) {    
    
      try {
      
          sendFrame( canDriver );

          receiveCanFrame( canDriver );
        
      } catch ( CanInitException& ex ) {

          std::cerr << "An error occurred while initializing CanDriver: " << ex.what( ) << std::endl;
      
      } catch ( CanException& ex ) {
      
        std::cerr << "CanException: " << ex.what( ) << std::endl;
      
      } catch ( InvalidSocketException& ex ) {
      
        std::cerr << "InvalidSocketException: " << ex.what( ) << std::endl;
      
      }
      
    
    }

}`

**Comment by lilgrant22** [comment]
Here's source code, stripped down. 

`enum {
  
    STATE1      = 0x0C602080,
    STATE2      = 0x0C612080,
    STATE3      = 0x0C622080, 
    STATEA      = 0x0C702080, 
    STATEB      = 0x0C712080, 
    STATEC      = 0x0C722080, 
    HEARTBEAT   = 0x18022080, 
    SEND1       = 0x0C648020, 
    ACK         = 0x0CE88020

};
 
double          x = 60;
double          y = 120;
unsigned char   z = 1;
bool            a = 0;
bool            b = 0;

}

void sendFrame( CanDriver* &driver ) {
    
    can_frame transmit_message;
    transmit_message.can_dlc = 8;
    
    unsigned short tmp = static_cast<unsigned short>( x / 0.01 );
    memcpy( &transmit_message.data[0], &tmp, sizeof( tmp ) );
    tmp = static_cast<unsigned short>( y / 0.1 );
    memcpy( &transmit_message.data[2], &tmp, sizeof( tmp ) );
    
    transmit_message.data[4] = 0;
    transmit_message.data[4] = ( static_cast<unsigned char>( z ) << 2 );
    transmit_message.data[4] += ( static_cast<unsigned char>( a ) << 1 );
    transmit_message.data[4] += ( static_cast<unsigned char>( b ) ); 
    
    transmit_message.can_id = SYS_CONT_DATA1;

    CanMessage sys_cont_data1 ( transmit_message );
    driver->sendMessage( sys_cont_data1 );

}

void receiveCanFrame( CanDriver* &driver ) {
        
    if ( !driver->waitForMessages( ) ) {  }
        
      std::queue<CanMessage> CanMessages = driver->readQueuedMessages( );

      while( !CanMessages.empty( ) ) {

          auto msg = CanMessages.front( );
          CanMessages.pop( );

          if( msg.getCanId( ) == HEARTBEAT ) {
              
              try {
              
                CanMessage send_ACK ( 0x0CE88020, "ACK" );
                driver->sendMessage( send_ACK );

                return;
                
              } catch ( CanException& ex ) {
              
                std::cerr << "Failed to send ACK Message (void receiveCanFrame( )): " << ex.what( ) << std::endl;
              
              }

          }
          
}


int main( ) {
    
    CanDriver* canDriver;
    canDriver = new CanDriver( "can0", CAN_RAW );
    
    
    while ( true ) {    
    
      try {
      
          sendFrame( canDriver );

          receiveCanFrame( canDriver );
        
      } catch ( CanInitException& ex ) {

          std::cerr << "An error occurred while initializing CanDriver: " << ex.what( ) << std::endl;
      
      } catch ( CanException& ex ) {
      
        std::cerr << "CanException: " << ex.what( ) << std::endl;
      
      } catch ( InvalidSocketException& ex ) {
      
        std::cerr << "InvalidSocketException: " << ex.what( ) << std::endl;
      
      }
      
    
    }

}`

**Comment by lilgrant22** [comment]
Source code, stripped down.

`void sendFrame( CanDriver* &driver ) {
    
    can_frame transmit_message;
    transmit_message.can_dlc = 8;
    
    unsigned short tmp = static_cast<unsigned short>( x / 0.01 );
    memcpy( &transmit_message.data[0], &tmp, sizeof( tmp ) );
    tmp = static_cast<unsigned short>( y / 0.1 );
    memcpy( &transmit_message.data[2], &tmp, sizeof( tmp ) );
    
    transmit_message.data[4] = 0;
    transmit_message.data[4] = ( static_cast<unsigned char>( z ) << 2 );
    transmit_message.data[4] += ( static_cast<unsigned char>( a ) << 1 );
    transmit_message.data[4] += ( static_cast<unsigned char>( b ) ); 
    
    transmit_message.can_id = SEND1;

    CanMessage send1 ( transmit_message );
    driver->sendMessage( send1 );

}`

`void receiveCanFrame( CanDriver* &driver ) {
        
    if ( !driver->waitForMessages( ) ) {  }
        
      std::queue<CanMessage> CanMessages = driver->readQueuedMessages( );

      while( !CanMessages.empty( ) ) {

          auto msg = CanMessages.front( );
          CanMessages.pop( );

          if( msg.getCanId( ) == HEARTBEAT ) {
              
              try {
              
                CanMessage send_ACK ( 0x0CE88020, "ACK" );
                driver->sendMessage( send_ACK );

                return;
                
              } catch ( CanException& ex ) {
              
                std::cerr << "Failed to send ACK Message (void receiveCanFrame( )): " << ex.what( ) << std::endl;
              
              }

          }
          
}`

**Comment by SimonCahill** [comment]
Hi there!

Generally speaking, CAN-IDs on Linux don't just contain the arbitration ID, but also contain information about bus errors and the message type.

In your case, it seems the `CAN_EFF_FLAG` is set, but the library isn't parsing this out and is returning a "faulty" value.
This definitely seems to be a bug in the library. 

Concerning the faulty values being sent; I don't think I've seen this behaviour before.
I'll try and reproduce it.

**Comment by lilgrant22** [comment]
Okay I think I spoke a bit hastily about the data being sent. I think I am running into an issue where I'm shifting the bits on byte 5, and I don't currently think that is a library issue at the moment. 

About the CAN IDs, the error I described has been replicated several times on my end, examples:

Known ID                                               returned from getCanID
0x0C602080                                          0x8C602080
0x0C612080                                          0x8C612080
0x18022080                                           0x98022080

From this it appears that the first digit in the hex values is being shifted twice to the left, changing 0 to 8, and 1 to 9.

**Comment by SimonCahill** [comment]
I'm currently working on a fix branch to remedy the issue.
The issue is with the `CanId` type.

I'll link this issue when I'm done with the PR. Because I'm both self-employed and working full-time, I don't always have time to sort these things super quickly. I'm on it, though! :)

**Comment by lilgrant22** [comment]
No worries at all. Thanks for the help.
