### ISSUE TITLE
CanId

### ISSUE THREAD

**Issue by illegal-instruction-co** [SimonCahill/libsockcanpp#6]
I'm using the CanId class in my project to manage CAN message identifiers. However, I've noticed that when I pass an extended frame ID, such as 0x70000000, to the constructor, the class incorrectly identifies it as a standard frame ID.

After some investigation, I believe the issue is that the class is not properly masking the ID to only include the 11 bits that represent the CAN identifier. I tried updating the constructor to mask the ID using the bitwise AND operator like this:

CanId(const uint32_t identifier): _identifier(identifier & 0x7FF)

However, this did not solve the issue. I also noticed that the CanId class already has bitwise operators defined, such as '&' and '|', but I'm not sure how to use them to correctly identify extended frame IDs.

Could someone please help me identify the root cause of this issue and suggest a solution?

Thank you.

**Comment by SimonCahill** [comment]
You're absolutely right!

Checking the source code, it seems I've introduced a typo causing the check to fail.

```cpp
CanId(const uint32_t identifier): _identifier(identifier) {
                if (isValidIdentifier(identifier)) {                    
                    if (((int32_t)log2(identifier) + 1) > 11) // this is wrong
                        _isStandardFrameId = true;
                    else _isExtendedFrameId = true;
                } else if (isErrorFrame(identifier)) {
                    _isErrorFrame = true;
                } else if (isRemoteTransmissionRequest(identifier)) {
                    _isRemoteTransmissionRequest = true;
                }
            }
```

The check should be `((int32_t)log2(identifier) + 1) > 11`.

I think I have a branch laying around, but currently not much hardware to test with. 
I'll update this issue with a feature branch, if you could test the feature branch and report back, I'd appreciate it!

This probably didn't show up in my internal usage because of the overloaded assignment operators:

```cpp
CanId canId = 0x1afffe;
```

**Comment by SimonCahill** [comment]
Please check out [this branch](https://github.com/SimonCahill/libsockcanpp/tree/fix_invalid_id_length_check) and see if it fixes your issue.

**Comment by illegal-instruction-co** [comment]
I will test it tomorrow on hardware and let you know on this issue. Thanks for quick response 🙃

**Comment by SimonCahill** [comment]
Okay, let me know when you've got some news!

**Comment by illegal-instruction-co** [comment]
> Okay, let me know when you've got some news!

Literally issue has been solved.

**Comment by SimonCahill** [comment]
I'll merge the fix into master.
