### ISSUE TITLE
Is the message seperated or not

### ISSUE THREAD

**Issue by illegal-instruction-co** [SimonCahill/libsockcanpp#9]
It may be wrong question, but is there a way to detect can message seperated into multiple can messages or single frame? 
I read CF FF, but i couldnt see any implementation in libsockcanpp.

Thank you.

**Comment by SimonCahill** [comment]
If you want to read multiple CAN messages, you can either simply poll `readMessage()`, or if you want to read the entire CAN buffer, `readQueuedMessages()` will return a `std::queue` with the CAN messages read from the bus.

Detecting multiple contiguous messages is hard, you'd need to identify them by their CAN ID, or using a protocol on top of CAN such as ISOTP: https://github.com/SimonCahill/isotp-c

**Comment by illegal-instruction-co** [comment]
> If you want to read multiple CAN messages, you can either simply poll `readMessage()`, or if you want to read the entire CAN buffer, `readQueuedMessages()` will return a `std::queue` with the CAN messages read from the bus.
> 
> Detecting multiple contiguous messages is hard, you'd need to identify them by their CAN ID, or using a protocol on top of CAN such as ISOTP: https://github.com/SimonCahill/isotp-c

I think the issue on my end is " could'nt understand the relationship between FF, FC and CF. I think isotp has over logic then my needs, and i want to implement simple detection contiguous messages by using FF, FC and FC's. Thank you to sharing these good sources. it was really helpful to understand some blinks.
